[project]
name = 'kyc-registry'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attester-registry]
path = 'contracts/attester-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.attester-registry-trait]
path = 'contracts/attester-registry-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.kyc-registry]
path = 'contracts/kyc-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.revocation]
path = 'contracts/revocation.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
